Repository OMZigak/KKUMER, pull requests merged in 2024-09, with the labels that each got.

#121 [fix] 약속 나가기 시 약속 참여 인원에 따른 약속 삭제
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
Labels: fix, 🐩 채원 🐩

#124 [fix] CI/CD 수정
  .github/workflows/dev-cd.yml
  .github/workflows/prod-cd.yml
Labels: fix

#125 [fix] CI/CD 수정
  .github/workflows/dev-cd.yml
Labels: dev

#130 [fix] CI/CD 트리거 고치기
  .github/workflows/dev-cd.yml
  .github/workflows/prod-cd.yml
Labels: fix, 🐩 채원 🐩

#128 [fix] 디스코드 로깅 오류 해결
  src/main/java/org/kkumulkkum/server/log/discord/DiscordAppender.java
Labels: fix, :black_cat: 상준 :black_cat:, 🐩 채원 🐩

#131 prod Deploy
  .github/workflows/dev-cd.yml
  .github/workflows/prod-cd.yml
  src/main/java/org/kkumulkkum/server/log/discord/DiscordAppender.java
Labels: deploy

#135 [fix] 모임 나가기 세부사항 수정
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
Labels: fix, 🐩 채원 🐩

#145 [fix] HttpMessageNotReadableException 핸들링 추가
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
Labels: fix, :black_cat: 상준 :black_cat:

#147 [fix] FCM deprecated method 변경
  build.gradle
  src/main/java/org/kkumulkkum/server/external/FcmService.java
Labels: fix, 🐩 채원 🐩

#149 [fix] 회원탈퇴 시 혼자 만든 약속 삭제하도록 수정
  src/main/java/org/kkumulkkum/server/repository/MemberRepository.java
  src/main/java/org/kkumulkkum/server/service/auth/AuthService.java
Labels: fix, 🐩 채원 🐩

#150 Release v1.0.1
  build.gradle
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
  src/main/java/org/kkumulkkum/server/external/FcmService.java
  src/main/java/org/kkumulkkum/server/repository/MemberRepository.java
  src/main/java/org/kkumulkkum/server/service/auth/AuthService.java
Labels: deploy
