Repository OMZigak/KKUMER, pull requests merged in 2024-07, with the labels that each got.

#13 [feat] #12 공통 응답 형태 클라 요청 반영
  src/main/java/org/kkumulkkum/server/dto/common/ResponseDto.java
Labels: feat, 🐩 채원 🐩

#14 [feat] 작업 전 기본 도메인 및 계층 세팅
  src/main/java/org/kkumulkkum/server/config/JpaAuditingConfig.java
  src/main/java/org/kkumulkkum/server/domain/BaseTimeEntity.java
  src/main/java/org/kkumulkkum/server/domain/Meeting.java
  src/main/java/org/kkumulkkum/server/domain/Member.java
  src/main/java/org/kkumulkkum/server/domain/Participant.java
  src/main/java/org/kkumulkkum/server/domain/Promise.java
  src/main/java/org/kkumulkkum/server/domain/User.java
  src/main/java/org/kkumulkkum/server/domain/UserInfo.java
  src/main/java/org/kkumulkkum/server/domain/enums/DressUpLevel.java
  src/main/java/org/kkumulkkum/server/domain/enums/Provider.java
  src/main/java/org/kkumulkkum/server/domain/enums/Role.java
  src/main/java/org/kkumulkkum/server/repository/MeetingRepository.java
  src/main/java/org/kkumulkkum/server/repository/MemberRepository.java
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java
  src/main/java/org/kkumulkkum/server/repository/UserInfoRepository.java
  src/main/java/org/kkumulkkum/server/repository/UserRepository.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
  src/main/java/org/kkumulkkum/server/service/member/MemberService.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
  src/main/java/org/kkumulkkum/server/service/user/UserService.java
  src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoService.java
Labels: feat, :black_cat: 상준 :black_cat:, 🐩 채원 🐩

#19 [feat] 소셜 로그인 구현
  build.gradle
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/apple/AppleFeignClient.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/apple/dto/ApplePublicKey.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/apple/dto/ApplePublicKeys.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/apple/service/AppleService.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/apple/verify/AppleJwtParser.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/apple/verify/PublicKeyGenerator.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/KakaoFeignClient.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/dto/KakaoAccount.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/dto/KakaoUserDto.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/dto/SocialUserDto.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/service/KakaoService.java
  src/main/java/org/kkumulkkum/server/config/FeignClientConfig.java
  src/main/java/org/kkumulkkum/server/config/SecurityConfig.java
  src/main/java/org/kkumulkkum/server/controller/AuthController.java
  src/main/java/org/kkumulkkum/server/domain/Token.java
  src/main/java/org/kkumulkkum/server/domain/UserInfo.java
  src/main/java/org/kkumulkkum/server/dto/auth/request/UserLoginDto.java
  src/main/java/org/kkumulkkum/server/exception/UserException.java
  src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/UserErrorCode.java
  src/main/java/org/kkumulkkum/server/repository/TokenRepository.java
  src/main/java/org/kkumulkkum/server/repository/UserRepository.java
  src/main/java/org/kkumulkkum/server/service/auth/AuthService.java
  src/main/java/org/kkumulkkum/server/service/auth/TokenSaver.java
  src/main/java/org/kkumulkkum/server/service/user/UserRetriever.java
  src/main/java/org/kkumulkkum/server/service/user/UserSaver.java
  src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRetriever.java
  src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoSaver.java
Labels: feat, 🐩 채원 🐩

#25 [feat] 참여자 도메인 API 일부 생성
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
  src/main/java/org/kkumulkkum/server/controller/ParticipantController.java
  src/main/java/org/kkumulkkum/server/controller/PromiseController.java
  src/main/java/org/kkumulkkum/server/domain/Participant.java
  src/main/java/org/kkumulkkum/server/exception/ParticipantException.java
  src/main/java/org/kkumulkkum/server/exception/code/ParticipantErrorCode.java
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantEditor.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
Labels: feat, :black_cat: 상준 :black_cat:

#29 [feat] 약속 관련 API 구현
  src/main/java/org/kkumulkkum/server/controller/PromiseController.java
  src/main/java/org/kkumulkkum/server/domain/enums/DressUpLevel.java
  src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java
  src/main/java/org/kkumulkkum/server/dto/promise/response/PromisesDto.java
  src/main/java/org/kkumulkkum/server/exception/PromiseException.java
  src/main/java/org/kkumulkkum/server/exception/code/PromiseErrorCode.java
  src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseRetriever.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
Labels: feat, 🐩 채원 🐩

#32 [feat] 약속 참여자 관련 API 구현
  src/main/java/org/kkumulkkum/server/controller/ParticipantController.java
  src/main/java/org/kkumulkkum/server/domain/Participant.java
  src/main/java/org/kkumulkkum/server/dto/participant/ParticipantStatusUserInfoDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/ParticipantUserInfoDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/request/PreparationInfoDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/LateComerDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/LateComersDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/ParticipantDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/ParticipantsDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/PreparationStatusDto.java
  src/main/java/org/kkumulkkum/server/exception/code/ParticipantErrorCode.java
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantEditor.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
Labels: feat, 🐩 채원 🐩

#37 [feat] 권한 확인 Annotation 제작
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
  src/main/java/org/kkumulkkum/server/annotation/IsMember.java
  src/main/java/org/kkumulkkum/server/annotation/IsParticipant.java
  src/main/java/org/kkumulkkum/server/aspect/MemberCheckAspect.java
  src/main/java/org/kkumulkkum/server/aspect/ParticipantCheckAspect.java
  src/main/java/org/kkumulkkum/server/controller/ParticipantController.java
  src/main/java/org/kkumulkkum/server/controller/PromiseController.java
  src/main/java/org/kkumulkkum/server/exception/MemberException.java
  src/main/java/org/kkumulkkum/server/exception/code/MemberErrorCode.java
  src/main/java/org/kkumulkkum/server/repository/MemberRepository.java
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/service/member/MemberRetreiver.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
Labels: feat, :black_cat: 상준 :black_cat:

#43 [feat] 약속 지각 상세 조회 API 추가 작업
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
Labels: feat, 🐩 채원 🐩

#44 [fix] 권한 확인용 annotation 조건문 수정
  src/main/java/org/kkumulkkum/server/annotation/IsMember.java
  src/main/java/org/kkumulkkum/server/aspect/MemberCheckAspect.java
Labels: fix, :black_cat: 상준 :black_cat:, 🐩 채원 🐩

#45 [fix] 약속 완료 API 수정
  src/main/java/org/kkumulkkum/server/controller/PromiseController.java
  src/main/java/org/kkumulkkum/server/domain/UserInfo.java
  src/main/java/org/kkumulkkum/server/dto/user/response/UserDto.java
  src/main/java/org/kkumulkkum/server/exception/code/PromiseErrorCode.java
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java
  src/main/java/org/kkumulkkum/server/repository/UserInfoRepository.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseRetriever.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
  src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRetriever.java
Labels: feat, :black_cat: 상준 :black_cat:

#48 [feat] 소셜 로그인 API 관련 수정 작업 (fcm Token 추가)
  src/main/java/org/kkumulkkum/server/controller/AuthController.java
  src/main/java/org/kkumulkkum/server/domain/UserInfo.java
  src/main/java/org/kkumulkkum/server/dto/auth/request/UserLoginDto.java
  src/main/java/org/kkumulkkum/server/dto/auth/response/UserTokenDto.java
  src/main/java/org/kkumulkkum/server/service/auth/AuthService.java
Labels: feat, 🐩 채원 🐩

#51 [fix] S3Service 이미지 외부 URL 생성
  src/main/java/org/kkumulkkum/server/external/S3Service.java
Labels: fix, 🐩 채원 🐩

#53 [fix] API 응답 관련 개선사항들 적용
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
  src/main/java/org/kkumulkkum/server/controller/MeetingController.java
  src/main/java/org/kkumulkkum/server/controller/UserController.java
  src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java
  src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingsDto.java
  src/main/java/org/kkumulkkum/server/dto/member/response/MemberDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/ParticipantStatusUserInfoDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/LateComerDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/ParticipantDto.java
  src/main/java/org/kkumulkkum/server/dto/promise/response/MainPromiseDto.java
  src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java
  src/main/java/org/kkumulkkum/server/dto/promise/response/PromisesDto.java
  src/main/java/org/kkumulkkum/server/dto/user/response/UserDto.java
  src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/AwsErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/BusinessErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/MeetingErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/MemberErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/OpenApiErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/ParticipantErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/PromiseErrorCode.java
  src/main/java/org/kkumulkkum/server/exception/code/UserErrorCode.java
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
  src/main/java/org/kkumulkkum/server/service/user/UserRetriever.java
  src/main/java/org/kkumulkkum/server/service/user/UserService.java
  src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRetriever.java
Labels: fix, :black_cat: 상준 :black_cat:, 🐩 채원 🐩

#55 [fix] 기타 로직 수정
  src/main/java/org/kkumulkkum/server/controller/LocationController.java
  src/main/java/org/kkumulkkum/server/controller/MeetingController.java
  src/main/java/org/kkumulkkum/server/controller/ParticipantController.java
  src/main/java/org/kkumulkkum/server/controller/PromiseController.java
  src/main/java/org/kkumulkkum/server/domain/Participant.java
  src/main/java/org/kkumulkkum/server/domain/Promise.java
  src/main/java/org/kkumulkkum/server/domain/User.java
  src/main/java/org/kkumulkkum/server/domain/UserInfo.java
  src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java
  src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingsDto.java
  src/main/java/org/kkumulkkum/server/dto/member/response/MembersDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/ParticipantStatusUserInfoDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/request/PreparationInfoDto.java
  src/main/java/org/kkumulkkum/server/dto/participant/response/PreparationStatusDto.java
  src/main/java/org/kkumulkkum/server/dto/test/TestDto.java
  src/main/java/org/kkumulkkum/server/external/NaverService.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingRetriever.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
  src/main/java/org/kkumulkkum/server/service/member/MemberRetreiver.java
  src/main/java/org/kkumulkkum/server/service/member/MemberService.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantEditor.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantSaver.java
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseEditor.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseRetriever.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseSaver.java
  src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
  src/main/java/org/kkumulkkum/server/service/user/UserRetriever.java
  src/main/java/org/kkumulkkum/server/service/user/UserSaver.java
  src/main/java/org/kkumulkkum/server/service/user/UserService.java
  src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoEditor.java
  src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoSaver.java
Labels: feat, :black_cat: 상준 :black_cat:, 🐩 채원 🐩

#59 [feat] 약속 참여자 목록 정렬 추가
  src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
Labels: feat, 🐩 채원 🐩

#61 [fix] 추가 개선사항 적용
  .gitignore
  src/main/java/org/kkumulkkum/server/annotation/IsMemberByMeetingId.java
  src/main/java/org/kkumulkkum/server/annotation/IsMemberByPromiseId.java
  src/main/java/org/kkumulkkum/server/aspect/MemberCheckAspect.java
  src/main/java/org/kkumulkkum/server/aspect/MemberCheckByMeetingIdAspect.java
  src/main/java/org/kkumulkkum/server/aspect/MemberCheckByPromiseIdAspect.java
  src/main/java/org/kkumulkkum/server/auth/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/kkumulkkum/server/auth/JwtAuthenticationFilter.java
  src/main/java/org/kkumulkkum/server/auth/jwt/JwtTokenProvider.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/apple/service/AppleService.java
  src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/service/KakaoService.java
  src/main/java/org/kkumulkkum/server/constant/AuthConstant.java
  src/main/java/org/kkumulkkum/server/controller/AuthController.java
  src/main/java/org/kkumulkkum/server/controller/LocationController.java
  src/main/java/org/kkumulkkum/server/controller/MeetingController.java
  src/main/java/org/kkumulkkum/server/controller/ParticipantController.java
  src/main/java/org/kkumulkkum/server/controller/PromiseController.java
  src/main/java/org/kkumulkkum/server/controller/TestController.java
  src/main/java/org/kkumulkkum/server/controller/UserController.java
  src/main/java/org/kkumulkkum/server/domain/Meeting.java
  src/main/java/org/kkumulkkum/server/external/FcmService.java
  src/main/java/org/kkumulkkum/server/external/NaverService.java
  src/main/java/org/kkumulkkum/server/repository/MeetingRepository.java
  src/main/java/org/kkumulkkum/server/repository/MemberRepository.java
  src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
  src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java
  src/main/java/org/kkumulkkum/server/repository/UserInfoRepository.java
Labels: fix, :black_cat: 상준 :black_cat:

#64 [fix] FCM 오류 수정
  src/main/java/org/kkumulkkum/server/config/AsyncConfig.java
  src/main/java/org/kkumulkkum/server/config/FirebaseConfig.java
  src/main/java/org/kkumulkkum/server/external/FcmService.java
  src/main/java/org/kkumulkkum/server/external/enums/FcmContent.java
Labels: fix, :black_cat: 상준 :black_cat:, 🐩 채원 🐩

#68 [fix] location 검색 API 수정
  src/main/java/org/kkumulkkum/server/controller/LocationController.java
  src/main/java/org/kkumulkkum/server/external/NaverService.java
  src/main/java/org/kkumulkkum/server/external/dto/LocationDto.java
  src/main/java/org/kkumulkkum/server/external/dto/LocationsDto.java
Labels: fix, :black_cat: 상준 :black_cat:

#72 [fix] 모임 가입 API에 응답값 추가
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
  src/main/java/org/kkumulkkum/server/controller/MeetingController.java
  src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingIdDto.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
Labels: fix, :black_cat: 상준 :black_cat:, 🐩 채원 🐩

#76 [fix] 약속 상세 정보 조회 API에 이름 추가
  src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java
Labels: fix, 🐩 채원 🐩

#80 [fix] 모임 생성 API에 반환 값에 meetingId 추가
  src/main/java/org/kkumulkkum/server/controller/MeetingController.java
  src/main/java/org/kkumulkkum/server/dto/meeting/response/CreatedMeetingDto.java
Labels: fix, 🐩 채원 🐩

#82 [fix] 모임 가입자 조회 API 쿼리 파라미터 추가
  src/main/java/org/kkumulkkum/server/controller/MeetingController.java
  src/main/java/org/kkumulkkum/server/domain/Participant.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
Labels: fix, :black_cat: 상준 :black_cat:

#83 [fix] 로그 레벨 수정 및 로그에 정보 추가
  src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
  src/main/java/org/kkumulkkum/server/log/discord/DiscordAppender.java
  src/main/java/org/kkumulkkum/server/log/filter/MDCFilter.java
  src/main/java/org/kkumulkkum/server/log/util/HttpRequestUtil.java
  src/main/java/org/kkumulkkum/server/log/util/MDCUtil.java
Labels: fix, :black_cat: 상준 :black_cat:

#85 [fix] API count 관련 이슈 해결
  src/main/java/org/kkumulkkum/server/dto/meeting/MeetingMetCountDto.java
  src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java
  src/main/java/org/kkumulkkum/server/repository/MeetingRepository.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingRetriever.java
  src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
Labels: fix, :black_cat: 상준 :black_cat:, 🐩 채원 🐩
